# Generated by Django 3.2.6 on 2021-08-29 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='customuser',
        ),
    ]
